=== peiris/ui/apps/www/public/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "style": {
      "type": "string",
      "enum": [
        "default"
      ]
    },
    "tailwind": {
      "type": "object",
      "properties": {
        "config": {
          "type": "string"
        },
        "css": {
          "type": "string"
        },
        "baseColor": {
          "type": "string"
        },
        "cssVariables": {
          "type": "boolean"
        }
      },
      "required": [
        "config",
        "css",
        "baseColor",
        "cssVariables"
      ]
    },
    "rsc": {
      "type": "boolean"
    },
    "tsx": {
      "type": "boolean"
    },
    "aliases": {
      "type": "object",
      "properties": {
        "utils": {
          "type": "string"
        },
        "components": {
          "type": "string"
        }
      },
      "required": [
        "utils",
        "components"
      ]
    }
  },
  "required": [
    "style",
    "tailwind",
    "rsc",
    "aliases"
  ]
}

=== peiris/ui/templates/next-template/components.json
{
  "$schema": "https://bento-kit.com/schema.json",
  "style": "default",
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "app/globals.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "rsc": false,
  "aliases": {
    "utils": "@/lib/utils",
    "components": "@/components"
  }
}
